version: '2'

services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  user-service:
    container_name: user-service
    build:
      context: ../user-service/
    image: user-service:1.0
    environment:
      - USER_SERVICE_PORT=3000
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "3000:3000"
    depends_on:
      - consul
    networks:
      - sky-net

  product-service:
    container_name: product-service
    build:
      context: ../product-service/
    image: product-service:1.0
    environment:
      - PRODUCT_SERVICE_PORT=3001
      - CONSUL_HTTP_ADDR=consul:8500
    ports:
      - "3001:3001"
    depends_on:
      - consul
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge